//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStore.Transport.Http.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Transport.Http.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An app:service element MUST contain one or more app:workspace elements. 的本地化字符串。
        /// </summary>
        internal static string An_appservice_element_MUST_contain_one_or_more_appworkspace_elements {
            get {
                return ResourceManager.GetString("An_appservice_element_MUST_contain_one_or_more_appworkspace_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:accept element MUST contain value 的本地化字符串。
        /// </summary>
        internal static string atomaccept_element_MUST_contain_value {
            get {
                return ResourceManager.GetString("atomaccept_element_MUST_contain_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:entry elements MUST contain an atom:summary element 的本地化字符串。
        /// </summary>
        internal static string atomentry_elements_MUST_contain_an_atomsummary_element {
            get {
                return ResourceManager.GetString("atomentry_elements_MUST_contain_an_atomsummary_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:entry elements MUST contain exactly one atom:id element. 的本地化字符串。
        /// </summary>
        internal static string atomentry_elements_MUST_contain_exactly_one_atomid_element {
            get {
                return ResourceManager.GetString("atomentry_elements_MUST_contain_exactly_one_atomid_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:entry elements MUST contain exactly one atom:title element. 的本地化字符串。
        /// </summary>
        internal static string atomentry_elements_MUST_contain_exactly_one_atomtitle_element {
            get {
                return ResourceManager.GetString("atomentry_elements_MUST_contain_exactly_one_atomtitle_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:entry elements MUST contain exactly one atom:updated element. 的本地化字符串。
        /// </summary>
        internal static string atomentry_elements_MUST_contain_exactly_one_atomupdated_element {
            get {
                return ResourceManager.GetString("atomentry_elements_MUST_contain_exactly_one_atomupdated_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:entry elements MUST contain one or more atom:author elements 的本地化字符串。
        /// </summary>
        internal static string atomentry_elements_MUST_contain_one_or_more_atomauthor_elements {
            get {
                return ResourceManager.GetString("atomentry_elements_MUST_contain_one_or_more_atomauthor_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:feed elements MUST contain exactly one atom:id element. 的本地化字符串。
        /// </summary>
        internal static string atomfeed_elements_MUST_contain_exactly_one_atomid_element {
            get {
                return ResourceManager.GetString("atomfeed_elements_MUST_contain_exactly_one_atomid_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:feed elements MUST contain exactly one atom:title element. 的本地化字符串。
        /// </summary>
        internal static string atomfeed_elements_MUST_contain_exactly_one_atomtitle_element {
            get {
                return ResourceManager.GetString("atomfeed_elements_MUST_contain_exactly_one_atomtitle_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:feed elements MUST contain exactly one atom:updated element. 的本地化字符串。
        /// </summary>
        internal static string atomfeed_elements_MUST_contain_exactly_one_atomupdated_element {
            get {
                return ResourceManager.GetString("atomfeed_elements_MUST_contain_exactly_one_atomupdated_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:feed elements MUST contain one or more atom:author elements 的本地化字符串。
        /// </summary>
        internal static string atomfeed_elements_MUST_contain_one_or_more_atomauthor_elements {
            get {
                return ResourceManager.GetString("atomfeed_elements_MUST_contain_one_or_more_atomauthor_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:feed elements SHOULD contain one atom:link element with a rel attribute value of &apos;self&apos;. This is the preferred URI for retrieving Atom Feed Documents representing this Atom feed. 的本地化字符串。
        /// </summary>
        internal static string atomfeed_elements_SHOULD_contain_one_atomlink_element_with_a_rel_attribute_value_of_self {
            get {
                return ResourceManager.GetString("atomfeed_elements_SHOULD_contain_one_atomlink_element_with_a_rel_attribute_value_" +
                        "of_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 atom:link elements MUST have an href attribute, whose value MUST be a URI reference 的本地化字符串。
        /// </summary>
        internal static string atomlink_elements_MUST_have_an_href_attribute {
            get {
                return ResourceManager.GetString("atomlink_elements_MUST_have_an_href_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Person constructs MUST contain exactly one &apos;atom:name&apos; element. 的本地化字符串。
        /// </summary>
        internal static string Person_constructs_MUST_contain_exactly_one_atomname_element {
            get {
                return ResourceManager.GetString("Person_constructs_MUST_contain_exactly_one_atomname_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app:collection element MUST contain an &apos;href&apos; attribute, whose value gives the IRI of the Collection. 的本地化字符串。
        /// </summary>
        internal static string The_appcollection_element_MUST_contain_an_href_attribute {
            get {
                return ResourceManager.GetString("The_appcollection_element_MUST_contain_an_href_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app: collection element MUST contain one atom:title element. 的本地化字符串。
        /// </summary>
        internal static string The_appcollection_element_MUST_contain_one_atomtitle_element {
            get {
                return ResourceManager.GetString("The_appcollection_element_MUST_contain_one_atomtitle_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app:workspace element MUST contain one &apos;atom:title&apos; element 的本地化字符串。
        /// </summary>
        internal static string The_appworkspace_element_MUST_contain_one_atomtitle_element {
            get {
                return ResourceManager.GetString("The_appworkspace_element_MUST_contain_one_atomtitle_element", resourceCulture);
            }
        }
    }
}
